name: final_project
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  flutter_native_splash: ^2.4.1 # Add this line
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/welcome.jpg
    - assets/charlotte_courts.jpg
    - assets/colombiana.jpg
    - assets/old_hosanna.jpg
    - assets/old_masere.jpg
    - assets/Dufie_Platinum.jpg
    - assets/splash.jpg

flutter_native_splash:
  background_image: assets/splash.jpg 
  android: true
  # ios: true
  color: "#FFFFFF" 