name: final_project
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  flutter_native_splash: ^2.4.1 # Add this line
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  # fluttertoast:  ^9.0.0
  google_fonts: ^6.2.1
  provider: ^6.1.2
  url_launcher: ^6.3.0
  firebase_messaging: ^14.9.4
  flutter_phone_direct_caller: ^2.1.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  carousel_slider: ^4.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/welcome.jpg
    - assets/charlotte_courts.jpg
    - assets/colombiana.jpg
    - assets/old_hosanna.jpg
    - assets/old_masere.jpg
    - assets/Dufie_Platinum.jpg
    - assets/splash.jpg
    - assets/home_back.jpg
    - assets/Nothing_Here_Yet.jpg

flutter_native_splash:
  background_image: assets/splash.jpg 
  android: true
  # ios: true
  color: "#FFFFFF" 

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon.jpg



