// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgnqjAUi30lZ_dMbMIF3UPpfa0P3ZsugQ',
    appId: '1:1066733566647:web:7d2a03f3f30a6ac6e3ab32',
    messagingSenderId: '1066733566647',
    projectId: 'hostel-connect-ec50e',
    authDomain: 'hostel-connect-ec50e.firebaseapp.com',
    storageBucket: 'hostel-connect-ec50e.appspot.com',
    measurementId: 'G-ZSHTBH1ZW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeMwjaGsIJ0rhGFdUSr6ZDGMXC0EJ3tmQ',
    appId: '1:1066733566647:android:57b8700edd0b26cde3ab32',
    messagingSenderId: '1066733566647',
    projectId: 'hostel-connect-ec50e',
    storageBucket: 'hostel-connect-ec50e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5RmMYdQx-3BlJgJwBbM8-fzt-JQZawZQ',
    appId: '1:1066733566647:ios:b5c8319f57ac0436e3ab32',
    messagingSenderId: '1066733566647',
    projectId: 'hostel-connect-ec50e',
    storageBucket: 'hostel-connect-ec50e.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5RmMYdQx-3BlJgJwBbM8-fzt-JQZawZQ',
    appId: '1:1066733566647:ios:b5c8319f57ac0436e3ab32',
    messagingSenderId: '1066733566647',
    projectId: 'hostel-connect-ec50e',
    storageBucket: 'hostel-connect-ec50e.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgnqjAUi30lZ_dMbMIF3UPpfa0P3ZsugQ',
    appId: '1:1066733566647:web:1801049d9ad9a1f9e3ab32',
    messagingSenderId: '1066733566647',
    projectId: 'hostel-connect-ec50e',
    authDomain: 'hostel-connect-ec50e.firebaseapp.com',
    storageBucket: 'hostel-connect-ec50e.appspot.com',
    measurementId: 'G-XS3YX09Y1Z',
  );

}